all:server peer_1 peer_2 peer_3 peer_4 mirror
server:server.c
	gcc -o server server.c 
peer_1:peer_1.c
	gcc -o peer_1 peer_1.c 
peer_2:peer_2.c
	gcc -o peer_2 peer_2.c 
peer_3:peer_3.c
	gcc -o peer_3 peer_3.c 
peer_4:peer_4.c
	gcc -o peer_4 peer_4.c 
mirror:mirror.c
	gcc -o mirror mirror.c 
